### ISSUE TITLE
Extremely stretched 3d aspect ratio regardless of settings

### ISSUE THREAD

**Issue by BlinkzFox** [PARTYMANX/partymod-thps2#13]
The 2d menus and hud render fine but the 3d is extremely squashed regardless of which settings I change. I changed resolution, internal resolution, ran it windowed. Nothing was different. RTX 2080 Super on windows 10. Driver 546.33 WHQL.
![image](https://github.com/PARTYMANX/partymod-thps2/assets/99220871/849878e0-0e9f-4f8c-9a24-b9dee4afef41)
![image](https://github.com/PARTYMANX/partymod-thps2/assets/99220871/6d39b94b-2a5f-43d6-a340-e049edd3c4db)
![image](https://github.com/PARTYMANX/partymod-thps2/assets/99220871/00d3c339-a8c7-41b9-be8c-b2d94ac4e216)

**Comment by PARTYMANX** [comment]
were you previously using a widescreen patch by any chance?  the pixelaspectratio value is being modified in an unexpected way here

**Comment by BlinkzFox** [comment]
> were you previously using a widescreen patch by any chance? the pixelaspectratio value is being modified in an unexpected way here

Yep that was the issue. Previously had the cumulative patch but deleted the files thinking it would be fine. Used it on a fresh install and the issue did not persist. My bad lol

**Comment by PARTYMANX** [comment]
Good to hear!  I should probably add a note about possible conflicting files to the installation instructions as other patches often use dinput.dll or other regular looking dlls
