### ISSUE TITLE
in realtion to DCxDemo's THPS2 patch

### ISSUE THREAD

**Issue by recore67** [PARTYMANX/partymod-thps2#8]
this is cool but since both projects are active why not work together combine eachother's patch?

**Comment by PARTYMANX** [comment]
honestly, i wasn't even aware cumulative patch was on github (or in active development) until like a few days ago lol.  But there are still reasons I'm interested in keeping a separate patch:
* like THPS3 Levelmod (or rethawed, which uses some of my patches, for that matter), I see Cumulative Patch as a community extension of the game.  I'm instead focused on making a "definitive" version of the port, keeping to what was released back in 2000 (including restoring portions of the PSX original).
* My approach is to avoid any gameplay changes (things like turning off Big Drop and changing the framerate cap) in the interest of speedrunning, avoiding a minefield of allowed settings and having to verify those settings.  
* I like to be able to make large iterations fast.  I'm already considering a big change to support Activision Value and (maybe more importantly) Korean versions of the game

**Comment by recore67** [comment]
oh ok, that's awesome!
